id = "beanseeds-pro"
name = "Beanseeds Pro Theme"
version = "1.0.0"
schema_version = 1
authors = ["Daniil Shilo [tokiory] <tokiory.work@gmail.com>"]
description = "Beanseeds Pro is a refined adaptation of the classic Jellybeans theme, specifically designed for the Zed editor"
repository = "https://github.com/tokiory/beanseeds-pro"
